### PR TITLE
Added support for modern node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by andris9** [comment]
Any idea why the tests failed? You should also not remove the old node versions as this module is needed by apps using non-modern node versions

**Comment by amilajack** [comment]
Not sure. Maybe try clearing the cache an running the tests again.

**Comment by andris9** [comment]
I meant the tests in [Travis](https://travis-ci.org/andris9/encoding/jobs/151034728). There's an error for whatever reason

**Comment by amilajack** [comment]
Yup, that's what I was referring to. Try clearing the travis cache and re-run the tests.

**Comment by andris9** [comment]
No use, after several re-runs still failing

**Pull request closed without merging**
